### ISSUE TITLE
Support mass delete

### ISSUE THREAD

**Issue by plakhin** [f9webltd/laravel-deletable#13]
It would be nice to have support of mass delete, e.g. `User::where('is_archived', true)->delete()` . Something like `isMassDeletable(): bool`. Laravel `SoftDeletes` Trait supports mass delete, so its code may be helpful.

**Comment by ultrono** [comment]
Hi,

I'd definitly be open to a PR for that. Although I can;t see anything in the soft deleting trait that covers mass deletion specifically.

Cheers

**Comment by ultrono** [comment]
Closing as no reply
