### ISSUE TITLE
Update to Laravel 8

### ISSUE THREAD

**Issue by hgferreira** [f9webltd/laravel-deletable#3]
Hello,

Can you update the composer.json to support Laravel 8?

**Comment by ultrono** [comment]
Hi,

Laravel 8 was released a couple of hours ago 😄 

I'll take a look in next couple of days. I'm fairly sure the change required will only be an update to `composer.json`. 

In the meantime you're more than welcome to submit a PR.

Thanks

**Comment by ultrono** [comment]
Laravel 8 is now supported see [v1.0.2](https://github.com/f9webltd/laravel-deletable/releases/tag/1.0.2)
